require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.cmp"
require "user.colorschemes" -- change colorscheme.lua to use different colorscheme plugin eg. Starry tokyonight ...
require "user.lsp"
require "user.comment"
require "user.dashboard-nvim"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.oil"
require "user.bufferline"
require "user.mini-align"
require "user.nvim-surround"
